language: cpp
matrix:
  include:
    - os: linux
      env: NAME="linux appimage"
      sudo: required
      dist: trusty
      services: docker
      addons:
        apt:
          packages:
            - p7zip-full
      install: "docker pull quriouspixel/yuzu:latest"
      script: "docker run -e ENABLE_COMPATIBILITY_REPORTING --env-file .travis/common/travis-ci.env -v $(pwd):/dolphin-emu -v "$HOME/.ccache":/root/.ccache quriouspixel/yuzu:latest /bin/bash /yuzu/travis/appimage/docker.sh"
      after_success: "./travis/appimage/appimage.sh"
      cache: ccache
deploy:
  provider: releases
  api_key:
    secure: $GITHUB_OAUTH_TOKEN
  file_glob: true
  file: "artifacts/*"
  skip_cleanup: true
  on:
    tags: true
