language: cpp
matrix:
  include:
    - os: linux
      env: NAME="linux appimage"
      sudo: required
      dist: bionic
      services: docker
      addons:
        apt:
          packages:
            - p7zip-full 
            - curl
      script: 
            - curl -sLO "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
      after_success: 
            - mkdir ~/Artifacts
            - mv linuxdeployqt-continuous-x86_64.AppImage ~/Artifacts
      cache: ccache
deploy:
  provider: releases
  api_key:
    secure: $GITHUB_OAUTH_TOKEN
  file_glob: true
  file: "~/Artifacts/*"
  skip_cleanup: true
  on:
    tags: true
