language: cpp
matrix:
  include:
    - os: linux
      env: NAME="linux appimage"
      sudo: required
      dist: bionic
      services: docker
      addons:
        apt:
          packages:
            - p7zip-full 
            - curl
            - libxi-dev
            - libavcodec-dev
            - libudev-dev
            - libevdev-dev
            - libc6-dev
            - libavformat-dev
            - libavdevice-dev
            - libfmt-dev
            - qtbase5-dev
            - qttools5-dev
            - qtbase5-private-dev
            - qtdeclarative5-dev
	          - liblzma-dev
	          - x11-utils
      script: 
            - mkdir Build && cd Build
            - cmake .. -DLINUX_LOCAL_DEV=true        
            - make
            - ln -s ../../Data/Sys Binaries/
      after_success: 
            - mkdir ~/Artifacts
            - mv linuxdeployqt-continuous-x86_64.AppImage ~/Artifacts
deploy:
  provider: releases
  api_key:
    secure: $GITHUB_OAUTH_TOKEN
  file_glob: true
  file: "~/Artifacts/*"
  skip_cleanup: true
  draft: true
  on:
    tags: true
