sudo: false
language: cpp
services: docker
compiler:
  - gcc
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-8
    - cmake
install:
- "[ $CXX = g++ ] && export CXX=g++-8 || true"
- "[ $CXX = clang++ ] && export CXX=clang++-3.8 || true"
- mkdir -p "$HOME/.ccache"
- docker pull quriouspixel/yuzu:latest
- docker run -u root --env-file travis/common/travis-ci.env -v $(pwd):/dolphin -v "$HOME/.ccache":/root/.ccache quriouspixel/yuzu:latest /bin/bash /dolphin/travis/appimage/docker.sh
script:
  - mkdir build && cd build
  - cmake ..
  - make
  - make test

  
