language: cpp
matrix:
  include:
    - os: linux
      env: NAME="linux appimage"
      sudo: required
      dist: trusty
      services: docker
      addons:
        apt:
          packages:
            - p7zip-full
      before_install: 
        - docker pull quriouspixel/yuzu:latest
      install: 
        - docker run -e ENABLE_COMPATIBILITY_REPORTING --env-file travis/common/travis-ci.env -v $(pwd):/dolphin-emu -v "$HOME/.ccache":/root/.ccache quriouspixel/yuzu:latest /bin/bash
      script: 
        - cd $HOME
        - mkdir build && cd build
        - cmake /dolphin-emu -DLINUX_LOCAL_DEV=true
        - make
        - ln -s ../../Data/Sys Binaries/
      after_success: "./travis/appimage/appimage.sh"
      cache: ccache
deploy:
  provider: releases
  api_key:
    secure: $GITHUB_OAUTH_TOKEN
  file_glob: true
  file: "artifacts/*"
  skip_cleanup: true
  on:
    tags: true
