language: cpp
matrix:
  include:
    - os: linux
      env: NAME="linux appimage"
      sudo: required
      dist: bionic
      services: docker
      addons:
        apt:
          packages:
            - p7zip-full
            - libxi-dev
            - libavcodec-dev
            - libudev-dev
            - libevdev-dev
            - libc6-dev
            - libavformat-dev
            - libavdevice-dev
            - libfmt-dev
      before_install: 
        - docker pull quriouspixel/yuzu:latest 
        - docker run -e ENABLE_COMPATIBILITY_REPORTING --env-file travis/common/travis-ci.env -v $(pwd):/dolphin -v "$HOME/.ccache":/root/.ccache quriouspixel/yuzu:latest /bin/bash
      script: 
        - mkdir Build && cd Build
        - cmake .. -DLINUX_LOCAL_DEV=true -DQt5_DIR=$PWD/Externals/Qt
        - make
        - ln -s ../../Data/Sys Binaries/
      after_success: "./travis/appimage/appimage.sh"
      cache: ccache
deploy:
  provider: releases
  api_key:
    secure: $GITHUB_OAUTH_TOKEN
  file_glob: true
  file: "artifacts/*"
  skip_cleanup: true
  on:
    tags: true
