name: Lint

on:
  push:
    branches: [ ios-jb ]
  pull_request:
    branches: [ ios-jb ]

jobs:
  run-linter:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
      - name: Lint
        run: | 
          echo ::set-env name=base_commit::$(git rev-parse ${{ github.base_ref }})
          echo ${{ env.base_commit }}
          ./Tools/lint.sh $(git rev-parse ${{ github.base_ref }})
      
