name: Lint

on:
  push:
    branches: [ ios-jb ]
  pull_request:
    branches: [ ios-jb ]

jobs:
  run-linter:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
      - name: Lint
        run: | 
          echo $BASE_COMMIT
          ./Tools/lint.sh $BASE_COMMIT
        env: 
          BASE_COMMIT: $(git rev-parse ${{ github.base_ref }})
      
